// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfayjdmpzmjpzwtroryj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmYXlqZG1wem1qcHp3dHJvcnlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MTg3OTYsImV4cCI6MjA3MDE5NDc5Nn0.xKsA29dYLKoOz5xkRuw-iB8hc4LSFeG-i1OBKj4RkSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});